[package]
name = "atomic-task"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]
publish = false

[dependencies]
cfg-if = "0.1.6"
futures = "0.1.25"
syncbox-fuzz = { path = "../../syncbox-fuzz", features = ["futures", "fringe"] }
