[package]
name = "fuzz-atomic-task"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[workspace]

[dependencies]
cfg-if = "0.1.6"
futures = "0.1.25"
syncbox-fuzz = { path = "../../syncbox-fuzz", features = ["futures"] }
